
stages:
  - sanity_checks
  - containers
  - builds

.script_variables: &script_variables |
  export MAKEFLAGS="-j$(getconf _NPROCESSORS_ONLN)"
  export SCRATCH_DIR="/tmp/scratch"
  export VROOT="$SCRATCH_DIR/vroot"
  export LIBDIR="$VROOT/lib"
  export CCACHE_DIR="$PWD/ccache"
  export CCACHE_MAXSIZE="500M"
  export PATH="$CCACHE_WRAPPERSDIR:$VROOT/bin:$PATH"
  export PKG_CONFIG_PATH="$LIBDIR/pkgconfig"
  export LD_LIBRARY_PATH="$LIBDIR"

.native_git_build_job:
  extends: .gitlab_native_build_job
  cache:
    paths:
      - ccache/
    key: "$CI_JOB_NAME"
  before_script:
    - *script_variables
  script:
    - pushd "$PWD"
    - mkdir -p "$SCRATCH_DIR"
    - cd "$SCRATCH_DIR"
    - git clone --depth 1 https://gitlab.com/libvirt/libvirt.git
    - cd libvirt
    - meson build -Ddriver_libvirtd=disabled "--prefix=$VROOT" "--libdir=$LIBDIR"
    - ninja -C build install
    - popd
    - mkdir build
    - cd build
    - ../autogen.sh --prefix="$VROOT"
    - $MAKE install
    - $MAKE dist
    - if test -x /usr/bin/rpmbuild ; then rpmbuild --nodeps -ta libvirt-snmp*.tar.gz ; fi

.native_build_job:
  extends: .gitlab_native_build_job
  cache:
    paths:
      - ccache/
    key: "$CI_JOB_NAME"
  before_script:
    - *script_variables
  script:
    - mkdir build
    - cd build
    - ../autogen.sh --prefix="$VROOT"
    - $MAKE install
    - $MAKE dist
    - if test -x /usr/bin/rpmbuild ; then rpmbuild -ta libvirt-snmp*.tar.gz ; fi

include: '/ci/gitlab.yml'
