/*
 * Note: this file originally auto-generated by mib2c using
 *       version : 14170 $ of $
 *
 * $Id:$
 */
#ifndef LIBVIRTGUESTTABLE_DATA_ACCESS_H
#define LIBVIRTGUESTTABLE_DATA_ACCESS_H

#ifdef __cplusplus
extern "C" {
#endif


/* *********************************************************************
 * function declarations
 */

/* *********************************************************************
 * Table declarations
 */
/**********************************************************************
 **********************************************************************
 ***
 *** Table libvirtGuestTable
 ***
 **********************************************************************
 **********************************************************************/
/*
 * LIBVIRT-MIB::libvirtGuestTable is subid 1 of libvirtObjects.
 * Its status is Current.
 * OID: .1.3.6.1.4.1.12345.1.1, length: 9
*/


    int libvirtGuestTable_init_data(libvirtGuestTable_registration * libvirtGuestTable_reg);


    /*
     * TODO:180:o: Review libvirtGuestTable cache timeout.
     * The number of seconds before the cache times out
     */
#define LIBVIRTGUESTTABLE_CACHE_TIMEOUT   5

void libvirtGuestTable_container_init(netsnmp_container **container_ptr_ptr,
                             netsnmp_cache *cache);
void libvirtGuestTable_container_shutdown(netsnmp_container *container_ptr);

int libvirtGuestTable_container_load(netsnmp_container *container);
void libvirtGuestTable_container_free(netsnmp_container *container);

int libvirtGuestTable_cache_load(netsnmp_container *container);
void libvirtGuestTable_cache_free(netsnmp_container *container);

    /*
    ***************************************************
    ***             START EXAMPLE CODE              ***
    ***---------------------------------------------***/
/* *********************************************************************
 * Since we have no idea how you really access your data, we'll go with
 * a worst case example: a flat text file.
 */
#define MAX_LINE_SIZE 256
    /*
    ***---------------------------------------------***
    ***              END  EXAMPLE CODE              ***
    ***************************************************/
    int libvirtGuestTable_row_prep( libvirtGuestTable_rowreq_ctx *rowreq_ctx);

int libvirtGuestTable_validate_index( libvirtGuestTable_registration * libvirtGuestTable_reg,
                               libvirtGuestTable_rowreq_ctx *rowreq_ctx);
int libvirtGuestUUID_check_index( libvirtGuestTable_rowreq_ctx *rowreq_ctx ); /* internal */


#ifdef __cplusplus
}
#endif

#endif /* LIBVIRTGUESTTABLE_DATA_ACCESS_H */
