/*
 * Note: this file originally auto-generated by mib2c using
 *  : generic-table-oids.m2c 17548 2009-04-23 16:35:18Z hardaker $
 *
 * $Id:$
 */
#ifndef LIBVIRTGUESTTABLE_OIDS_H
#define LIBVIRTGUESTTABLE_OIDS_H

#ifdef __cplusplus
extern "C" {
#endif


/* column number definitions for table libvirtGuestTable */
#define LIBVIRTGUESTTABLE_OID              1,3,6,1,4,1,12345,1,1


#define COLUMN_LIBVIRTGUESTUUID         1
    
#define COLUMN_LIBVIRTGUESTNAME         2
    
#define COLUMN_LIBVIRTGUESTSTATE         3
#define COLUMN_LIBVIRTGUESTSTATE_FLAG    (0x1 << 0)
    
#define COLUMN_LIBVIRTGUESTCPUCOUNT         4
    
#define COLUMN_LIBVIRTGUESTMEMORYCURRENT         5
    
#define COLUMN_LIBVIRTGUESTMEMORYLIMIT         6
    
#define COLUMN_LIBVIRTGUESTCPUTIME         7
    
#define COLUMN_LIBVIRTGUESTROWSTATUS         9
#define COLUMN_LIBVIRTGUESTROWSTATUS_FLAG    (0x1 << 1)
    

#define LIBVIRTGUESTTABLE_MIN_COL   COLUMN_LIBVIRTGUESTNAME
#define LIBVIRTGUESTTABLE_MAX_COL   COLUMN_LIBVIRTGUESTROWSTATUS
    

    /*
     * TODO:405:r: Review LIBVIRTGUESTTABLE_SETTABLE_COLS macro.
     * OR together all the writable cols.
     */
#define LIBVIRTGUESTTABLE_SETTABLE_COLS (COLUMN_LIBVIRTGUESTSTATE_FLAG | COLUMN_LIBVIRTGUESTROWSTATUS_FLAG)
    /*
     * TODO:405:r: Review LIBVIRTGUESTTABLE_REQUIRED_COLS macro.
     * OR together all the required rows for row creation.
     * default is writable cols w/out defaults.
     */
#define LIBVIRTGUESTTABLE_REQUIRED_COLS (COLUMN_LIBVIRTGUESTSTATE_FLAG | COLUMN_LIBVIRTGUESTROWSTATUS_FLAG)
    

#ifdef __cplusplus
}
#endif

#endif /* LIBVIRTGUESTTABLE_OIDS_H */
